#ifndef USER_SPRAY_HEADER_H_
#define USER_SPRAY_HEADER_H_

#include <CONVERGE/udf.h>

// User Lagrangian Data Field IDs
CONVERGE_id_t USER_LAG_VAR;
CONVERGE_id_t USER_LAG_VARi;
CONVERGE_id_t USER_LAG_VARv3;
CONVERGE_id_t USER_LAG_VARv3b;
CONVERGE_id_t R_BUBBLE;
CONVERGE_id_t V_BUBBLE;
CONVERGE_id_t R_B_0;
CONVERGE_id_t R_B_TM1;
CONVERGE_id_t V_B_TM1;
CONVERGE_id_t V_DROP;
CONVERGE_id_t R_D_0;				//Droplet Radius when injected
CONVERGE_id_t R_THERM;
CONVERGE_id_t OMEGA;				//DGRE root
CONVERGE_id_t OMEGA_TM1;
CONVERGE_id_t INT_OMEGA;
CONVERGE_id_t ETA;				//Integral of omega - breakup criterion
CONVERGE_id_t ETA_0;				//Integral of omega - breakup criterion
CONVERGE_id_t USER_LAG_VARi;
CONVERGE_id_t DGRE_COUNT;
CONVERGE_id_t PARCEL_INDEX;             // Parcel Index
CONVERGE_id_t CLOUD_INDEX;             // Cloud Index
CONVERGE_id_t THERMAL_BREAKUP_FLAG;		//Flag to indicate that thermal breakup has taken place
CONVERGE_id_t TBT;
CONVERGE_id_t IS_CHILD;
CONVERGE_id_t PBT;
CONVERGE_id_t CHILD_INDEX;
CONVERGE_id_t M0;
CONVERGE_id_t CHILD_UU;				//Child UU vector


// Lagrangian Data Field IDs
CONVERGE_id_t LAGRANGIAN_REL_VEL;
CONVERGE_id_t LAGRANGIAN_UPRIME;
CONVERGE_id_t LAGRANGIAN_UU;
CONVERGE_id_t LAGRANGIAN_ISBIG;
CONVERGE_id_t LAGRANGIAN_FROM_INJECTOR;
CONVERGE_id_t LAGRANGIAN_FROM_INJECTOR_TYPE;
CONVERGE_id_t LAGRANGIAN_V_NU;
CONVERGE_id_t LAGRANGIAN_V_SH;
CONVERGE_id_t LAGRANGIAN_TEMP;
CONVERGE_id_t LAGRANGIAN_TEMP_TM1;
CONVERGE_id_t LAGRANGIAN_TEMP_STARM1;
CONVERGE_id_t LAGRANGIAN_REY_NUM;
CONVERGE_id_t LAGRANGIAN_REL_VEL_MAG;
CONVERGE_id_t LAGRANGIAN_RADIUS;
CONVERGE_id_t LAGRANGIAN_RADIUS_TM1;
CONVERGE_id_t LAGRANGIAN_PARENT;
CONVERGE_id_t LAGRANGIAN_DENSITY;
CONVERGE_id_t LAGRANGIAN_DENSITY_TM1;
CONVERGE_id_t LAGRANGIAN_MFRAC;
CONVERGE_id_t LAGRANGIAN_MFRAC_TM1;
CONVERGE_id_t LAGRANGIAN_NUM_DROP;
CONVERGE_id_t LAGRANGIAN_SURF_TEN;
CONVERGE_id_t LAGRANGIAN_VISCOSITY;
CONVERGE_id_t LAGRANGIAN_DISTORT;
CONVERGE_id_t LAGRANGIAN_DISTORT_DOT;
CONVERGE_id_t LAGRANGIAN_SURF_TEMP;
CONVERGE_id_t LAGRANGIAN_TBREAK_KH;
CONVERGE_id_t LAGRANGIAN_SHED_NUM_DROP;
CONVERGE_id_t LAGRANGIAN_SHED_MASS;
CONVERGE_id_t LAGRANGIAN_SACTIVE;
CONVERGE_id_t LAGRANGIAN_SACTIVE_TM1;
CONVERGE_id_t LAGRANGIAN_DM_DT;
CONVERGE_id_t LAGRANGIAN_DRDT;
CONVERGE_id_t LAGRANGIAN_WALL_HEAT_EXCHANGE;
CONVERGE_id_t LAGRANGIAN_L_RR;
CONVERGE_id_t LAGRANGIAN_L_RC;
CONVERGE_id_t LAGRANGIAN_L_TEMP1;
CONVERGE_id_t LAGRANGIAN_L_TEMP2;
CONVERGE_id_t LAGRANGIAN_JUST_HIT;
CONVERGE_id_t LAGRANGIAN_JUST_HIT_LEIDEN;
CONVERGE_id_t LAGRANGIAN_ISTHICK;
CONVERGE_id_t LAGRANGIAN_FILM_SHED;
CONVERGE_id_t LAGRANGIAN_XX;
CONVERGE_id_t LAGRANGIAN_XX_TM1;
CONVERGE_id_t LAGRANGIAN_ON_TRIANGLE;
CONVERGE_id_t LAGRANGIAN_FROM_NOZZLE;
CONVERGE_id_t LAGRANGIAN_TBREAK_RT;
CONVERGE_id_t LAGRANGIAN_SURF_TEMP_TM1;
CONVERGE_id_t LAGRANGIAN_NUM_DROP_TM1;
CONVERGE_id_t LAGRANGIAN_FILM_FLAG;
CONVERGE_id_t LAGRANGIAN_FILM_ENERGY;
CONVERGE_id_t LAGRANGIAN_T_TURB;
CONVERGE_id_t LAGRANGIAN_T_TURB_ACCUM;
CONVERGE_id_t LAGRANGIAN_FILM_THICKNESS;
CONVERGE_id_t LAGRANGIAN_AREA_IN_FILM;
CONVERGE_id_t LAGRANGIAN_FILM_THICKNESS_TM1;
CONVERGE_id_t LAGRANGIAN_AREA_REDUCTION;
CONVERGE_id_t LAGRANGIAN_TKE0;
CONVERGE_id_t LAGRANGIAN_EPS0;
CONVERGE_id_t LAGRANGIAN_LIFETIME;
CONVERGE_id_t LAGRANGIAN_UU_TM1;
CONVERGE_id_t LAGRANGIAN_GAS_DENSITY;
CONVERGE_id_t LAGRANGIAN_FILM_ACCUM_BIT_FLAG;
CONVERGE_id_t LAGRANGIAN_FILM_ACCUM_PLUS_BIT_FLAG;

// Nozzle Parameter IDs
CONVERGE_id_t NOZZLE_AXIAL_VEC;
CONVERGE_id_t NOZZLE_NORMAL_VEC;
CONVERGE_id_t NOZZLE_OTHER_VEC;
CONVERGE_id_t NOZZLE_AREA;
CONVERGE_id_t NOZZLE_DIAMETER;
CONVERGE_id_t NOZZLE_LENGTH;
CONVERGE_id_t NOZZLE_SMD_DISTRIBUTION;
CONVERGE_id_t NOZZLE_AMP_DISTORT;
CONVERGE_id_t NOZZLE_CONE_ANGLE;
CONVERGE_id_t NOZZLE_THICKNESS;
CONVERGE_id_t NOZZLE_RADIAL_DISTANCE;
CONVERGE_id_t NOZZLE_AXIAL_DISTANCE;
CONVERGE_id_t NOZZLE_POSITION_VEC;
CONVERGE_id_t NOZZLE_XX_VEC;
CONVERGE_id_t NOZZLE_YY_VEC;
CONVERGE_id_t NOZZLE_ZZ_VEC;
CONVERGE_id_t NOZZLE_POSITION;
CONVERGE_id_t NOZZLE_X;
CONVERGE_id_t NOZZLE_Y;
CONVERGE_id_t NOZZLE_Z;
CONVERGE_id_t NOZZLE_MAX_DISTANCE;
CONVERGE_id_t NOZZLE_PENETRATION;
CONVERGE_id_t NOZZLE_VAPOR_PENETRATION;
CONVERGE_id_t NOZZLE_ECN_PENETRATION;
CONVERGE_id_t NOZZLE_TOTAL_MASS;
CONVERGE_id_t NOZZLE_RADIUS_INJECT;
CONVERGE_id_t NOZZLE_VOL_COUNT;
CONVERGE_id_t NOZZLE_CONE_INPUT_FLAG;
CONVERGE_id_t NOZZLE_DIAMETER_INPUT_FLAG;
CONVERGE_id_t NOZZLE_RADIUS_INJECT_INPUT_FLAG;
CONVERGE_id_t NOZZLE_NOZ_THETA;
CONVERGE_id_t NOZZLE_NOZ_ANGLE_XY;
CONVERGE_id_t NOZZLE_NOZ_ANGLE_XZ;
// Injector Parameter IDs

CONVERGE_id_t INJECTOR_INJECTED_PARCEL_INDEX;
CONVERGE_id_t INJECTOR_INJECTED_PARCEL_TYPE;
CONVERGE_id_t INJECTOR_INJECTED_NUM_PARCEL_SPECIES;
CONVERGE_id_t INJECTOR_CONE_DISTRIBUTION_FLAG;
CONVERGE_id_t INJECTOR_DYNAMIC_SPRAY_CONE_ANGLE_FLAG;
CONVERGE_id_t INJECTOR_PENET_FRAC;
CONVERGE_id_t INJECTOR_VAPOR_PENET_FRAC;
CONVERGE_id_t INJECTOR_PENET_BIN_SIZE;
CONVERGE_id_t INJECTOR_MFRAC;
CONVERGE_id_t INJECTOR_START_INJECT_IS_FILE;
CONVERGE_id_t INJECTOR_DUR_INJECT_IS_FILE;
CONVERGE_id_t INJECTOR_MASS_INJECT_IS_FILE;
CONVERGE_id_t INJECTOR_NOZZLE_INIT_FLAG;
CONVERGE_id_t INJECTOR_SPRAY_INJECT_BC_FLAG;
CONVERGE_id_t INJECTOR_ELSA_FLAG;
CONVERGE_id_t INJECTOR_TEMP_FLAG;
CONVERGE_id_t INJECTOR_TKE_FLAG;
CONVERGE_id_t INJECTOR_EPS_FLAG;
CONVERGE_id_t INJECTOR_INIT_CELL_TURB_FLAG;
CONVERGE_id_t INJECTOR_KHACT_NOZZLE_FLOW_FLAG;
CONVERGE_id_t INJECTOR_KH_NEW_PARCEL_FLAG;
CONVERGE_id_t INJECTOR_KH_NO_ENLARGE_FLAG;
CONVERGE_id_t INJECTOR_INJECT_DISTRIBUTION_FLAG;
CONVERGE_id_t INJECTOR_RT_FLAG;
CONVERGE_id_t INJECTOR_RT_DISTRIBUTION_FLAG;
CONVERGE_id_t INJECTOR_TAB_FLAG;
CONVERGE_id_t INJECTOR_TAB_DISTRIBUTION_FLAG;
CONVERGE_id_t INJECTOR_LISA_FLAG;
CONVERGE_id_t INJECTOR_DISCHARGE_COEFF_INPUT_FLAG;
CONVERGE_id_t INJECTOR_LISA_DISTRIBUTION_FLAG;
CONVERGE_id_t INJECTOR_RATE_SHAPE_INPUT_FLAG;
CONVERGE_id_t INJECTOR_DISCHARGE_COEFF_FLAG;
CONVERGE_id_t INJECTOR_INJECT_INDEX;
CONVERGE_id_t INJECTOR_NUM_PARCELS_PER_NOZZLE;
CONVERGE_id_t INJECTOR_NUM_NOZZLES;
CONVERGE_id_t INJECTOR_STREAM_INDEX;
CONVERGE_id_t INJECTOR_NUM_INJECT_PARCELS;
CONVERGE_id_t INJECTOR_CONE_FLAG;
CONVERGE_id_t INJECTOR_TEMPORAL_TYPE;
CONVERGE_id_t INJECTOR_VELOCITY_COEFF_INPUT_FLAG;
CONVERGE_id_t INJECTOR_POLAR_CPY_NUM;
CONVERGE_id_t INJECTOR_Q_RR;
CONVERGE_id_t INJECTOR_GAMMA_RR_X_DIST;
CONVERGE_id_t INJECTOR_LISA_INJECTION_PRES;
CONVERGE_id_t INJECTOR_LISA_KV;
CONVERGE_id_t INJECTOR_CYCLIC_PERIOD;
CONVERGE_id_t INJECTOR_INJECT_START_TIME;
CONVERGE_id_t INJECTOR_INJECT_DURATION;
CONVERGE_id_t INJECTOR_END_INJECT;
CONVERGE_id_t INJECTOR_INJECT_MASS;
CONVERGE_id_t INJECTOR_INJECT_TEMP;
CONVERGE_id_t INJECTOR_AREA;
CONVERGE_id_t INJECTOR_KH_NEW_PARCEL_CUTOFF;
CONVERGE_id_t INJECTOR_KH_SHED_FACTOR;
CONVERGE_id_t INJECTOR_KH_BALPHA;
CONVERGE_id_t INJECTOR_KH_CONST1;
CONVERGE_id_t INJECTOR_KH_CONST2;
CONVERGE_id_t INJECTOR_RT_LENGTH_CONST;
CONVERGE_id_t INJECTOR_RT_CONST3;
CONVERGE_id_t INJECTOR_RT_CONST2;
CONVERGE_id_t INJECTOR_KHACT_TURB_KC;
CONVERGE_id_t INJECTOR_KHACT_TURB_KE;
CONVERGE_id_t INJECTOR_KHACT_TURB_S;
CONVERGE_id_t INJECTOR_KHACT_C_TCAV;
CONVERGE_id_t INJECTOR_TIME_OFFSET;
CONVERGE_id_t INJECTOR_MASS_PER_PARCEL;
CONVERGE_id_t INJECTOR_VELOCITY;
CONVERGE_id_t INJECTOR_VELOCITY_TM1;
CONVERGE_id_t INJECTOR_VELOCITY_OUT_OLD;
CONVERGE_id_t INJECTOR_VELOCITY_OUT_NEW;
CONVERGE_id_t INJECTOR_VELOCITY_COEFF;
CONVERGE_id_t INJECTOR_MASS_TM1;
CONVERGE_id_t INJECTOR_MASS_TM2;
CONVERGE_id_t INJECTOR_DISCHARGE_COEFF;
CONVERGE_id_t INJECTOR_RATE_SHAPE;
CONVERGE_id_t INJECTOR_ANGLE_XY_INJ;
CONVERGE_id_t INJECTOR_ANGLE_XZ_INJ;
CONVERGE_id_t INJECTOR_ANGLE_CLOCK_INJ;
CONVERGE_id_t INJECTOR_RHO_LIQUID;
CONVERGE_id_t INJECTOR_SWIRL_FRAC;
CONVERGE_id_t INJECTOR_TOT_INJECTED_MASS;
CONVERGE_id_t INJECTOR_TOT_INJECTED_MASS_TM;
CONVERGE_id_t INJECTOR_AZIMUTH_ANGLE_START;
CONVERGE_id_t INJECTOR_AZIMUTH_ANGLE_END;
CONVERGE_id_t INJECTOR_SCALE_TEMP;
CONVERGE_id_t INJECTOR_OFFSET_TEMP;
CONVERGE_id_t INJECTOR_INJECT_TKE;
CONVERGE_id_t INJECTOR_SCALE_TKE;
CONVERGE_id_t INJECTOR_OFFSET_TKE;
CONVERGE_id_t INJECTOR_INJECT_EPS;
CONVERGE_id_t INJECTOR_SCALE_EPS;
CONVERGE_id_t INJECTOR_OFFSET_EPS;
CONVERGE_id_t INJECTOR_SWIRLER_MASS_FLOW_RATE;
CONVERGE_id_t INJECTOR_SWIRLER_MEAN_ANGLE;
CONVERGE_id_t INJECTOR_SWIRLER_RADIUS;
CONVERGE_id_t INJECTOR_VOF_SPRAY_MASS_PER_PARCEL;
CONVERGE_id_t INJECTOR_VOF_SPRAY_LIQ_FRAC_THRESHOLD;
CONVERGE_id_t INJECTOR_X_CEN;
CONVERGE_id_t INJECTOR_AXI_VEC;
CONVERGE_id_t INJECTOR_NORM_VEC;
CONVERGE_id_t INJECTOR_OTHER_VEC;
// Boundary Injector Parameter IDs

CONVERGE_id_t BOUNDARY_INJECTOR_SMD;
CONVERGE_id_t BOUNDARY_INJECTOR_CYCLIC_PERIOD;
CONVERGE_id_t BOUNDARY_INJECTOR_END_INJECT;
CONVERGE_id_t BOUNDARY_INJECTOR_INJECT_START_TIME;
CONVERGE_id_t BOUNDARY_INJECTOR_INJECT_DURATION;
CONVERGE_id_t BOUNDARY_INJECTOR_VELOCITY;
CONVERGE_id_t BOUNDARY_INJECTOR_VELOCITY_TM1;
CONVERGE_id_t BOUNDARY_INJECTOR_TOT_INJ_MASS;
CONVERGE_id_t BOUNDARY_INJECTOR_TOT_INJ_MASS_TM;
CONVERGE_id_t BOUNDARY_INJECTOR_INJECT_TEMP;
CONVERGE_id_t BOUNDARY_INJECTOR_Q_RR;
CONVERGE_id_t BOUNDARY_INJECTOR_RATE_SHAPE;
CONVERGE_id_t BOUNDARY_INJECTOR_TOT_AREA;
CONVERGE_id_t BOUNDARY_INJECTOR_MASS_PER_PARCEL;
CONVERGE_id_t BOUNDARY_INJECTOR_MASS_TM1;
CONVERGE_id_t BOUNDARY_INJECTOR_MASS_TM2;
CONVERGE_id_t BOUNDARY_INJECTOR_INJECT_MASS;
CONVERGE_id_t BOUNDARY_INJECTOR_VELOCITY_OLD_OUT;
CONVERGE_id_t BOUNDARY_INJECTOR_VELOCITY_OLD_NEW;
CONVERGE_id_t BOUNDARY_INJECTOR_PARCEL_RADIUS;
CONVERGE_id_t BOUNDARY_INJECTOR_AMP_DISTORT;
CONVERGE_id_t BOUNDARY_INJECTOR_GAMMA_RR_X_DIST;
CONVERGE_id_t BOUNDARY_INJECTOR_INJECT_RATIO_VALUE;
CONVERGE_id_t BOUNDARY_INJECTOR_MFRAC;

// Dynamic IDs for parcel setups
CONVERGE_id_t PARCEL_IN_BREAKUP_FLAG;
CONVERGE_id_t PARCEL_IN_KH_FLAG;
CONVERGE_id_t PARCEL_IN_KH_NEW_PARCEL_FLAG;
CONVERGE_id_t PARCEL_IN_KH_NO_ENLARGE_FLAG;
CONVERGE_id_t PARCEL_IN_KH_NEW_PARCEL_CUTOFF;
CONVERGE_id_t PARCEL_IN_KH_SHED_FACTOR;
CONVERGE_id_t PARCEL_IN_KH_VEL_CONST;
CONVERGE_id_t PARCEL_IN_KH_SIZE_CONST;
CONVERGE_id_t PARCEL_IN_KH_TIME_CONST;
CONVERGE_id_t PARCEL_IN_KHACT_TURB_KC;
CONVERGE_id_t PARCEL_IN_KHACT_TURB_KE;
CONVERGE_id_t PARCEL_IN_KHACT_TURB_S;
CONVERGE_id_t PARCEL_IN_KHACT_C_TCAV;
CONVERGE_id_t PARCEL_IN_RT_FLAG;
CONVERGE_id_t PARCEL_IN_RT_DISTRIBUTION_FLAG;
CONVERGE_id_t PARCEL_IN_RT_TIME_CONST;
CONVERGE_id_t PARCEL_IN_RT_SIZE_CONST;
CONVERGE_id_t PARCEL_IN_RT_LENGTH_CONST;
CONVERGE_id_t PARCEL_IN_TAB_FLAG;
CONVERGE_id_t PARCEL_IN_TAB_DISTRIBUTION_FLAG;
CONVERGE_id_t PARCEL_IN_TAB_CSUBD;
CONVERGE_id_t PARCEL_IN_TAB_CSUBK;
CONVERGE_id_t PARCEL_IN_LISA_FLAG;
CONVERGE_id_t PARCEL_IN_LISA_DISTRIBUTION_FLAG;
CONVERGE_id_t PARCEL_IN_LISA_LENGTH_CONST;
CONVERGE_id_t PARCEL_IN_LISA_SIZE_CONST;

// Solid parcel Data Field IDs
CONVERGE_id_t SOLID_PARCEL_REL_VEL;
CONVERGE_id_t SOLID_PARCEL_UPRIME;
CONVERGE_id_t SOLID_PARCEL_UU;
CONVERGE_id_t SOLID_PARCEL_FROM_INJECTOR;
CONVERGE_id_t SOLID_PARCEL_FROM_INJECTOR_TYPE;
CONVERGE_id_t SOLID_PARCEL_V_NU;
CONVERGE_id_t SOLID_PARCEL_TEMP;
CONVERGE_id_t SOLID_PARCEL_TEMP_TM1;
CONVERGE_id_t SOLID_PARCEL_TEMP_STARM1;
CONVERGE_id_t SOLID_PARCEL_REY_NUM;
CONVERGE_id_t SOLID_PARCEL_REL_VEL_MAG;
CONVERGE_id_t SOLID_PARCEL_RADIUS;
CONVERGE_id_t SOLID_PARCEL_RADIUS_TM1;
CONVERGE_id_t SOLID_PARCEL_DENSITY;
CONVERGE_id_t SOLID_PARCEL_DENSITY_TM1;
CONVERGE_id_t SOLID_PARCEL_MFRAC;
CONVERGE_id_t SOLID_PARCEL_MFRAC_TM1;
CONVERGE_id_t SOLID_PARCEL_NUM_DROP;
CONVERGE_id_t SOLID_PARCEL_VISCOSITY;
CONVERGE_id_t SOLID_PARCEL_DISTORT;
CONVERGE_id_t SOLID_PARCEL_SURF_TEMP;
CONVERGE_id_t SOLID_PARCEL_JUST_HIT;
CONVERGE_id_t SOLID_PARCEL_XX;
CONVERGE_id_t SOLID_PARCEL_XX_TM1;
CONVERGE_id_t SOLID_PARCEL_ON_TRIANGLE;
CONVERGE_id_t SOLID_PARCEL_FROM_NOZZLE;
CONVERGE_id_t SOLID_PARCEL_SURF_TEMP_TM1;
CONVERGE_id_t SOLID_PARCEL_NUM_DROP_TM1;
CONVERGE_id_t SOLID_PARCEL_FILM_FLAG;
CONVERGE_id_t SOLID_PARCEL_T_TURB;
CONVERGE_id_t SOLID_PARCEL_T_TURB_ACCUM;
CONVERGE_id_t SOLID_PARCEL_UU_TM1;

// Dynamic IDs for parcel setups
CONVERGE_id_t PARCELS_IN_SOLID_PARCELS_DRAG_MODEL;
CONVERGE_id_t PARCELS_IN_SOLID_PARCELS_WALL_INTERACTION_FLAG;
CONVERGE_id_t PARCELS_IN_SOLID_PARCELS_COEFF_OF_RESTITUTION_TYPE;
CONVERGE_id_t PARCELS_IN_SOLID_PARCELS_COEFF_OF_RESTITUTION_NORMAL_DIR;
CONVERGE_id_t PARCELS_IN_SOLID_PARCELS_COEFF_OF_RESTITUTION_TANG_DIR;
CONVERGE_id_t PARCELS_IN_SOLID_PARCELS_STICK_RATE;

// User Parcel Cloud structure for caching cloud field data
struct ParcelCloud
{
   // User data
   CONVERGE_precision_t* user_temp_starm1;
   CONVERGE_int_t* user_lag_var_i;
   CONVERGE_vec3_t* user_lag_var_v3;
   CONVERGE_vec3_t* user_lag_var_v3b;
   CONVERGE_precision_t* r_bubble;
   CONVERGE_precision_t* v_bubble;
   CONVERGE_precision_t* v_drop;
   CONVERGE_precision_t* r_bubble_0;
   CONVERGE_precision_t* v_bubble_tm1;
   CONVERGE_precision_t* r_drop_0;
   CONVERGE_precision_t* r_therm;
   CONVERGE_precision_t* omega;
   CONVERGE_precision_t* omega_tm1;
   CONVERGE_precision_t* int_omega;
   CONVERGE_precision_t * eta_drop;
   CONVERGE_precision_t * eta_drop_0;
   CONVERGE_precision_t * r_bubble_tm1;
   CONVERGE_precision_t * m0;
   CONVERGE_int_t* parcel_index;
   CONVERGE_int_t* cloud_index;
   CONVERGE_int_t* thermal_breakup_flag;
   CONVERGE_int_t* dgre_cycle_count;
   CONVERGE_int_t* tbt;
   CONVERGE_int_t* pbt;
   CONVERGE_int_t* child_index;
   CONVERGE_int_t* is_child;

   // CONVERGE data
   int* from_injector;
   int* from_injector_type;
   int* on_triangle;
   int* from_nozzle;
   int* film_flag;

   unsigned long long* film_accum_bit_flag;
   unsigned int* film_accum_plus_bit_flag;

   short* just_hit;
   short* just_hit_leiden;
   char* is_thick;

   CONVERGE_vec3_t* rel_vel;
   CONVERGE_vec3_t* uprime;
   CONVERGE_vec3_t* uu;
   CONVERGE_vec3_t* uu_tm1;
   CONVERGE_vec3_t* child_uu;
   CONVERGE_vec3_t* xx; // adding a comment
   CONVERGE_vec3_t* xx_tm1;
   CONVERGE_vec3_t* drop_gas_src;

   CONVERGE_precision_t* v_nu;
   CONVERGE_precision_t* v_sh;
   CONVERGE_precision_t* temp;
   CONVERGE_precision_t* temp_tm1;
   CONVERGE_precision_t* temp_starm1;
   CONVERGE_precision_t* rey_num;
   CONVERGE_precision_t* rel_vel_mag;
   CONVERGE_precision_t* radius;
   CONVERGE_precision_t* radius_tm1;
   CONVERGE_precision_t* parent;
   CONVERGE_precision_t* density;
   CONVERGE_precision_t* density_tm1;
   CONVERGE_precision_t* gas_density;
   CONVERGE_precision_t* mfrac;
   CONVERGE_precision_t* mfrac_tm1;
   CONVERGE_precision_t* num_drop;
   CONVERGE_precision_t* surf_ten;
   CONVERGE_precision_t* viscosity;
   CONVERGE_precision_t* distort;
   CONVERGE_precision_t* distort_dot;
   CONVERGE_precision_t* surf_temp;
   CONVERGE_precision_t* tbreak_kh;
   CONVERGE_precision_t* shed_num_drop;
   CONVERGE_precision_t* shed_mass;
   CONVERGE_precision_t* sactive;
   CONVERGE_precision_t* sactive_tm1;
   CONVERGE_precision_t* dm_dt;
   CONVERGE_precision_t* drdt;
   CONVERGE_precision_t* wall_heat_exchange;
   CONVERGE_precision_t* l_rr;
   CONVERGE_precision_t* l_rc;
   CONVERGE_precision_t* l_temp1;
   CONVERGE_precision_t* l_temp2;
   CONVERGE_precision_t* film_shed;
   CONVERGE_precision_t* tbreak_rt;
   CONVERGE_precision_t* surf_temp_tm1;
   CONVERGE_precision_t* num_drop_tm1;
   CONVERGE_precision_t* film_energy;
   CONVERGE_precision_t* t_turb;
   CONVERGE_precision_t* t_turb_accum;
   CONVERGE_precision_t* film_thickness;
   CONVERGE_precision_t* area_in_film;
   CONVERGE_precision_t* film_thickness_tm1;
   CONVERGE_precision_t* area_reduction;
   CONVERGE_precision_t* tke0;
   CONVERGE_precision_t* eps0;
   CONVERGE_precision_t* lifetime;
   CONVERGE_precision_t* force_coefficient;
};

void load_user_cloud(struct ParcelCloud*, CONVERGE_cloud_t c);

void load_user_solid_parcel_cloud(struct ParcelCloud*, CONVERGE_cloud_t c);

void load_species_tables(CONVERGE_iterator_t it, CONVERGE_index_t table_id, CONVERGE_table_t** tables);
void unload_species_tables(CONVERGE_iterator_t it, CONVERGE_table_t** tables);
double get_parcel_prop_from_table(CONVERGE_iterator_t it,
                                  CONVERGE_table_t** table,
                                  CONVERGE_precision_t temp,
                                  CONVERGE_precision_t* mfrac,
                                  CONVERGE_index_t is_density);

#define SAFE_calloc(num, type) (type*)calloc(num, sizeof(type));

#endif   // USER_HEADER_H_
