#include <CONVERGE/udf.h>

CONVERGE_EXTERN CONVERGE_id_t LAG_UU;
CONVERGE_EXTERN CONVERGE_id_t LAG_MFRAC;
CONVERGE_EXTERN CONVERGE_id_t LAG_RADIUS;
CONVERGE_EXTERN CONVERGE_id_t LAG_RHO;
CONVERGE_EXTERN CONVERGE_id_t LAG_NDROP;
